import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/letter_template.dart';
import 'evidence_pdf_export.dart' show sanitizeForPdf;

/// Renders a generated letter to a single-page PDF: a small internal
/// heading, the letter body, and the "not legal advice" disclaimer
/// required on every letter (build_execution.md Phase 7).
///
/// Hindi and Kannada need a font with Devanagari/Kannada glyph coverage —
/// the `pdf` package's built-in fonts only cover Latin script, so those
/// languages would otherwise render as blank boxes (same failure mode
/// fixed for ₹/↓/→ in Evidence's PDF export). [PdfGoogleFonts] downloads
/// the matching Noto Sans variant on first use — this needs network
/// access, same as the app's existing Gemini calls.
Future<Uint8List> buildLetterPdf({
  required LetterTemplateType type,
  required LetterLanguage lang,
  required String body,
}) async {
  final font = await _fontFor(lang);
  final doc = pw.Document();

  doc.addPage(
    pw.MultiPage(
      build: (context) => [
        pw.Text(
          type.label,
          style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, font: font),
        ),
        pw.SizedBox(height: 20),
        pw.Text(
          sanitizeForPdf(body),
          style: pw.TextStyle(fontSize: 12, font: font, lineSpacing: 2),
        ),
        pw.SizedBox(height: 24),
        pw.Divider(),
        pw.Text(
          sanitizeForPdf(
            'Generated by AsliKamai. This is an information request, not legal '
            'advice. Draft template — pending review by a labour lawyer or union.',
          ),
          style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700),
        ),
      ],
    ),
  );
  return doc.save();
}

Future<pw.Font?> _fontFor(LetterLanguage lang) {
  switch (lang) {
    case LetterLanguage.english:
      return Future.value(null);
    case LetterLanguage.hindi:
      return PdfGoogleFonts.notoSansDevanagariRegular();
    case LetterLanguage.kannada:
      return PdfGoogleFonts.notoSansKannadaRegular();
  }
}
