import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/painting.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../l10n/app_locale.dart';
import '../l10n/strings.dart';
import '../models/letter_template.dart';
import 'evidence_pdf_export.dart' show sanitizeForPdf;

const _disclaimer =
    'Generated by AsliKamai. This is an information request, not legal '
    'advice. Draft template — pending review by a labour lawyer or union.';

/// Renders a generated letter to a PDF: a small internal heading, the
/// letter body, and the "not legal advice" disclaimer required on every
/// letter (build_execution.md Phase 7).
///
/// English is drawn as real PDF text (selectable/searchable). Hindi and
/// Kannada can't be: the `pdf` package doesn't do complex-script shaping,
/// so vowel signs and conjuncts come out wrong in every font — verified
/// directly, e.g. दिनांक printed as "दनिांक" and ವಿ's sign detached. For
/// those, each page is laid out with Flutter's own text engine (which
/// shapes them correctly, same as the app's screens) and embedded as an
/// image. Trade-off: the text in those PDFs isn't selectable.
Future<Uint8List> buildLetterPdf({
  required LetterTemplateType type,
  required LetterLanguage lang,
  required String body,
}) {
  // The heading is written in the letter's language, not the app's.
  final title =
      Strings(AppLocale.values.byName(lang.name)).letterTemplateLabel(type.name);
  return switch (lang) {
    LetterLanguage.english => _buildTextPdf(title: title, body: body),
    LetterLanguage.hindi ||
    LetterLanguage.kannada =>
      _buildRasterPdf(title: title, body: body),
  };
}

Future<Uint8List> _buildTextPdf({
  required String title,
  required String body,
}) {
  final doc = pw.Document();
  doc.addPage(
    pw.MultiPage(
      build: (context) => [
        pw.Text(
          title,
          style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 20),
        pw.Text(
          sanitizeForPdf(body),
          style: const pw.TextStyle(fontSize: 12, lineSpacing: 2),
        ),
        pw.SizedBox(height: 24),
        pw.Divider(),
        pw.Text(
          sanitizeForPdf(_disclaimer),
          style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700),
        ),
      ],
    ),
  );
  return doc.save();
}

// A4 in PDF points, with the same 2cm margin pw.MultiPage uses by default.
final _pageWidth = PdfPageFormat.a4.width;
final _pageHeight = PdfPageFormat.a4.height;
const _margin = 2.0 * PdfPageFormat.cm;

// Rasterise at 3x points (~216 dpi): crisp when printed, ~100-200 KB/page.
const _pixelRatio = 3.0;

const _ink = Color(0xFF000000);
const _grey = Color(0xFF616161);

/// One vertical piece of the letter: laid-out text, a gap, or a rule.
sealed class _Block {}

class _TextBlock extends _Block {
  _TextBlock(this.painter);
  final TextPainter painter;
}

class _GapBlock extends _Block {
  _GapBlock(this.height);
  final double height;
}

class _RuleBlock extends _Block {
  static const height = 11.0;
}

/// A run of consecutive lines from one [_TextBlock], placed at [y] on a
/// page. [sourceTop]/[sourceBottom] are that run's extent within the
/// block's own layout.
class _Slice {
  _Slice(this.block, this.y, this.sourceTop, this.sourceBottom);
  final _Block block;
  final double y;
  final double sourceTop;
  final double sourceBottom;
}

Future<Uint8List> _buildRasterPdf({
  required String title,
  required String body,
}) async {
  final contentWidth = _pageWidth - 2 * _margin;
  final contentHeight = _pageHeight - 2 * _margin;

  TextPainter layout(String text, TextStyle style) {
    return TextPainter(
      text: TextSpan(text: text, style: style),
      textDirection: TextDirection.ltr,
    )..layout(maxWidth: contentWidth);
  }

  final blocks = <_Block>[
    _TextBlock(layout(
      title,
      const TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: _ink),
    )),
    _GapBlock(20),
    _TextBlock(layout(
      body,
      const TextStyle(fontSize: 12, height: 1.5, color: _ink),
    )),
    _GapBlock(24),
    _RuleBlock(),
    _TextBlock(layout(
      _disclaimer,
      const TextStyle(fontSize: 8, color: _grey),
    )),
  ];

  final pages = _paginate(blocks, contentHeight);

  final doc = pw.Document();
  for (final slices in pages) {
    final png = await _renderPage(slices, contentWidth);
    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: pw.EdgeInsets.zero,
        build: (_) => pw.Image(pw.MemoryImage(png), fit: pw.BoxFit.fill),
      ),
    );
  }
  for (final b in blocks) {
    if (b is _TextBlock) b.painter.dispose();
  }
  return doc.save();
}

/// Splits [blocks] into pages of at most [contentHeight], breaking text
/// only between lines so no line is ever cut in half.
List<List<_Slice>> _paginate(List<_Block> blocks, double contentHeight) {
  final pages = <List<_Slice>>[[]];
  var y = 0.0;

  void newPage() {
    pages.add([]);
    y = 0;
  }

  for (final block in blocks) {
    switch (block) {
      case _GapBlock(:final height):
        // A gap at the top of a page is just wasted space.
        if (y > 0) y += height;
      case _RuleBlock():
        if (y + _RuleBlock.height > contentHeight) newPage();
        pages.last.add(_Slice(block, y, 0, _RuleBlock.height));
        y += _RuleBlock.height;
      case _TextBlock(:final painter):
        final lines = painter.computeLineMetrics();
        var sliceTop = 0.0;
        var sliceY = y;
        for (var i = 0; i < lines.length; i++) {
          final line = lines[i];
          final lineTop = line.baseline - line.ascent;
          final lineBottom = i + 1 < lines.length
              ? lines[i + 1].baseline - lines[i + 1].ascent
              : painter.height;
          if (sliceY + (lineBottom - sliceTop) <= contentHeight) continue;
          if (lineTop > sliceTop) {
            // Close the slice before this line; it starts the next page.
            pages.last.add(_Slice(block, sliceY, sliceTop, lineTop));
            newPage();
            sliceTop = lineTop;
            sliceY = 0;
          } else if (sliceY > 0) {
            // Not even this block's first line fits under earlier content.
            newPage();
            sliceY = 0;
          }
        }
        pages.last.add(_Slice(block, sliceY, sliceTop, painter.height));
        y = sliceY + (painter.height - sliceTop);
    }
  }
  return pages.where((p) => p.isNotEmpty).toList();
}

Future<Uint8List> _renderPage(List<_Slice> slices, double contentWidth) async {
  final recorder = ui.PictureRecorder();
  final canvas = Canvas(recorder)
    ..scale(_pixelRatio)
    ..drawRect(
      Rect.fromLTWH(0, 0, _pageWidth, _pageHeight),
      Paint()..color = const Color(0xFFFFFFFF),
    )
    ..translate(_margin, _margin);

  for (final slice in slices) {
    switch (slice.block) {
      case _TextBlock(:final painter):
        canvas
          ..save()
          ..clipRect(Rect.fromLTWH(
            0,
            slice.y,
            contentWidth,
            slice.sourceBottom - slice.sourceTop,
          ));
        painter.paint(canvas, Offset(0, slice.y - slice.sourceTop));
        canvas.restore();
      case _RuleBlock():
        final ruleY = slice.y + _RuleBlock.height / 2;
        canvas.drawLine(
          Offset(0, ruleY),
          Offset(contentWidth, ruleY),
          Paint()
            ..color = _grey
            ..strokeWidth = 1,
        );
      case _GapBlock():
        break;
    }
  }

  final picture = recorder.endRecording();
  final image = await picture.toImage(
    (_pageWidth * _pixelRatio).round(),
    (_pageHeight * _pixelRatio).round(),
  );
  picture.dispose();
  final data = await image.toByteData(format: ui.ImageByteFormat.png);
  image.dispose();
  return data!.buffer.asUint8List();
}
